version: "3"
services:
    app:
        build: .
        command: go run main.go
        volumes:
            - ".:/go/src/github.com/projectweekend/cta-bus-predictions"
        environment:
            API_KEY: whatever
            STOP_IDS: 17772,587,5004
